### ISSUE TITLE
Tinder updates to 5.3.x versions

### ISSUE THREAD

**Issue by matheuseduardo** [Nadavrbn/TinderMods#1]
I'm using Tinder 5.0.5 version, since future updates is not working with "TinderMods".
_(and this mod is useful for me)_

I think it's because a huge visual upgrade in Tinder app., changing layouts and maybe methods to hook.

Do you plan updates? How could I be useful helping you in development?

**Comment by Nadavrbn** [comment]
Hi,

I have not experienced problems with any update of Tinder yet.
I'm running it on version 5.3.5 and it's working for me.
Please expand on what issues are you experiencing.

Cheers,
Nadav

**Comment by matheuseduardo** [comment]
@Nadavrbn I've checked now and you're right! May be module was not selected to be loaded. Or anything like that. Sorry to bother you. (And nice job! : ) :+1:
